version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rimq6mz5an2k"
s3_prefix = "hello-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
